pub mod abstraction_verify;
pub mod advanced_optimizer;
#[cfg(feature = "gnn-optimizer")]
pub mod advanced_self_repair;
pub mod autovec;
#[cfg(feature = "gnn-optimizer")]
pub mod gnn_egraph_optimizer;
#[cfg(feature = "gnn-optimizer")]
pub mod gnn_trained_weights;
pub mod hardware_cost_model;
pub mod inline_cache;
#[cfg(feature = "gnn-optimizer")]
pub mod mcts_superoptimizer;
pub mod memory_optimizer;
pub mod multi_tier_jit;
pub mod optimizer;
pub mod profile_guided;
pub mod self_repair;
pub mod data_dependent_jit;
#[cfg(feature = "gnn-optimizer")]
pub mod ml_superopt;
#[cfg(feature = "gnn-optimizer")]
pub mod polyhedral;
#[cfg(feature = "gnn-optimizer")]
pub mod semantic_superopt;
pub mod soa_optimizer;
#[cfg(feature = "phase3-jit")]
pub mod tiered_compilation;
