pub mod abstraction_verify;
pub mod advanced_optimizer;
#[cfg(feature = "gnn-optimizer")]
pub mod advanced_self_repair;
pub mod autovec;
#[cfg(feature = "gnn-optimizer")]
pub mod gnn_egraph_optimizer;
#[cfg(feature = "gnn-optimizer")]
pub mod gnn_trained_weights;
pub mod hardware_cost_model;
#[cfg(feature = "core-superopt")]
pub mod uarch_cost;
pub mod inline_cache;
#[cfg(any(feature = "gnn-optimizer", feature = "core-superopt"))]
pub mod mcts_superoptimizer;
#[cfg(feature = "core-superopt")]
pub mod mcts_core;
#[cfg(feature = "core-superopt")]
pub mod smt_verify;
pub mod memory_optimizer;
pub mod multi_tier_jit;
pub mod optimizer;
pub mod profile_guided;
pub mod self_repair;
pub mod data_dependent_jit;
#[cfg(feature = "gnn-optimizer")]
pub mod ml_superopt;
#[cfg(feature = "gnn-optimizer")]
pub mod polyhedral;
#[cfg(feature = "gnn-optimizer")]
pub mod semantic_superopt;
pub mod soa_optimizer;
#[cfg(feature = "phase3-jit")]
pub mod tiered_compilation;
pub mod partial_eval;
pub mod learned_scheduler;
pub mod alias_layout;
pub mod dead_field_elim;
#[cfg(feature = "core-superopt")]
pub mod known_bits;
pub mod superopt_pass;
