// =========================================================================
// Unified Superoptimizer Pass — Wired Pipeline
//
// This module connects the superoptimizer ecosystem to the compilation
// pipeline. It runs a multi-stage optimization pipeline:
//
//   Stage 1: Semantic Rewrites (120+ egg-style rules)
//   Stage 2: Known-Bits Pruning (fast pre-filter)
//   Stage 3: MCTS Tree Search (stochastic superoptimization)
//   Stage 4: SMT Verification (CEGIS + optional Z3)
//   Stage 5: uarch Cost Validation (dependency-DAG scheduling)
//
// Feature gates:
//   - core-superopt: Stages 2-5
//   - gnn-optimizer: Stage 1 (in addition to 2-5 when both enabled)
//   - smt-verify: Z3 formal proofs in Stage 4
//
// SuperoptMode from the AST drives the optimization level:
//   - None          → skip superoptimization entirely
//   - MctsSuperopt  → MCTS pipeline (stages 2-5), no semantic rewrites
//   - EGraph        → semantic rewrites + MCTS fast config
//   - MlSuperopt    → semantic rewrites + MCTS fast config
//   - All           → full pipeline including SMT verification
// =========================================================================

use std::time::Instant;

use crate::compiler::ast::{Expr, Item, Program, Stmt, SuperoptMode};

#[cfg(feature = "machine-instr-model")]
use crate::optimizer::machine_instr_model::{
    MachineInstrPipeline, MachineCostVector, estimate_machine_cost,
    lower_instr_to_machine, check_legality, validate_transformation,
};

// ── Feature-gated imports ──────────────────────────────────────────────────

#[cfg(any(feature = "core-superopt", feature = "gnn-optimizer"))]
use crate::optimizer::mcts_superoptimizer::{Instr as MctsInstr, MctsConfig, MctsSuperoptimizer};

#[cfg(feature = "core-superopt")]
use crate::optimizer::smt_verify::{CegisVerifier, VerifyResult};

#[cfg(feature = "core-superopt")]
use crate::optimizer::known_bits;

#[cfg(feature = "core-superopt")]
use crate::optimizer::uarch_cost::{self, MachineInstr, Opcode, TargetConfig};

#[cfg(feature = "gnn-optimizer")]
use crate::optimizer::semantic_superopt::SemanticSuperoptimizer;

#[cfg(feature = "core-superopt")]
use rustc_hash::FxHashMap;

// =========================================================================
// Statistics
// =========================================================================

/// Statistics from a superoptimization run.
#[derive(Debug, Clone, Default)]
pub struct SuperoptStats {
    /// Total number of expression nodes visited during the walk.
    pub expressions_visited: usize,
    /// Number of expressions that were actually replaced with optimized versions.
    pub expressions_optimized: usize,
    /// Number of candidate programs generated by MCTS search.
    pub mcts_candidates_generated: usize,
    /// Number of MCTS candidates that passed verification.
    pub mcts_candidates_verified: usize,
    /// Number of SMT (CEGIS) verifications performed.
    pub smt_verifications: usize,
    /// Number of semantic rewrite rules that fired (Stage 1).
    pub semantic_rewrites: usize,
    /// Number of candidates rejected by known-bits analysis (Stage 2).
    pub known_bits_rejections: usize,
    /// Number of candidates rejected because uarch cost was not better (Stage 5).
    pub uarch_rejections: usize,
    /// Number of candidates processed by the machine-instr pipeline (Stage 6).
    pub machine_instr_candidates: usize,
    /// Number of candidates rejected by machine-instr cost model (Stage 6).
    pub machine_instr_rejections: usize,
    /// Total wall-clock time spent in the pass, in microseconds.
    pub total_time_us: u64,
}

// =========================================================================
// Configuration
// =========================================================================

/// Configuration for the unified superoptimizer pass.
#[derive(Debug, Clone)]
pub struct SuperoptConfig {
    /// Maximum number of nodes in an expression's `Instr` tree for it to be
    /// considered for MCTS search. Larger expressions are skipped.
    pub max_expr_size: usize,
    /// Whether to verify equivalence with CEGIS before accepting a candidate.
    pub verify_equivalence: bool,
    /// Whether to use the uarch cost model to validate that the optimized
    /// version is actually cheaper on the target CPU.
    pub use_uarch_cost_model: bool,
    /// Bit width for SMT bitvector encoding (typically 64).
    pub smt_bitwidth: u32,
    /// Maximum number of CEGIS iterations per verification.
    pub cegis_max_iterations: usize,
}

impl Default for SuperoptConfig {
    fn default() -> Self {
        Self {
            max_expr_size: 64,
            verify_equivalence: true,
            use_uarch_cost_model: true,
            smt_bitwidth: 64,
            cegis_max_iterations: 10,
        }
    }
}

// =========================================================================
// SuperoptPass — the unified pipeline
// =========================================================================

/// The unified superoptimizer pass.
///
/// Wire together the disconnected superoptimizer modules into a single
/// compilation pipeline entry point.  Call `optimize_program(&mut Program)`
/// to run all enabled stages.
///
/// S10+S13 fix: Reuses a single MctsSuperoptimizer across expressions
/// and caches TargetConfig to avoid CPUID per expression.
pub struct SuperoptPass {
    config: SuperoptConfig,
    stats: SuperoptStats,
    /// S10 fix: Reuse a single MctsSuperoptimizer across expressions
    /// to avoid recreating HardwareCostModel (CPUID) per expression.
    #[cfg(any(feature = "core-superopt", feature = "gnn-optimizer"))]
    mcts_optimizer: Option<MctsSuperoptimizer>,
    /// S13 fix: Cache TargetConfig once instead of calling detect() per expression.
    #[cfg(feature = "core-superopt")]
    cached_target: Option<TargetConfig>,
}

impl SuperoptPass {
    /// Create a new superoptimizer pass with the given configuration.
    pub fn new(config: SuperoptConfig) -> Self {
        Self {
            config,
            stats: SuperoptStats::default(),
            #[cfg(any(feature = "core-superopt", feature = "gnn-optimizer"))]
            mcts_optimizer: None, // Lazy-initialized on first use
            #[cfg(feature = "core-superopt")]
            cached_target: None, // Lazy-initialized on first use
        }
    }

    /// Create a superoptimizer pass with default configuration.
    pub fn default_pass() -> Self {
        Self::new(SuperoptConfig::default())
    }

    /// Run the full superoptimization pipeline on a program, modifying it
    /// in place.  Returns a reference to the accumulated statistics.
    pub fn optimize_program(&mut self, program: &mut Program) -> &SuperoptStats {
        let start = Instant::now();

        match program.superopt_mode {
            SuperoptMode::None => {
                // Skip superoptimization entirely.
            }
            SuperoptMode::All => {
                self.run_pipeline(program, /* full_mode */ true);
            }
            SuperoptMode::MctsSuperopt => {
                // MCTS-only: no semantic rewrites, but full verification.
                self.run_pipeline(program, /* full_mode */ true);
            }
            SuperoptMode::EGraph | SuperoptMode::MlSuperopt => {
                // Semantic rewrites + MCTS fast config, skip SMT.
                self.run_pipeline(program, /* full_mode */ false);
            }
        }

        self.stats.total_time_us = start.elapsed().as_micros() as u64;
        &self.stats
    }

    /// Consume the pass and return the statistics.
    pub fn into_stats(self) -> SuperoptStats {
        self.stats
    }

    /// Return a reference to the accumulated statistics.
    pub fn stats(&self) -> &SuperoptStats {
        &self.stats
    }

    // ─────────────────────────────────────────────────────────────────────
    // Internal pipeline driver
    // ─────────────────────────────────────────────────────────────────────

    fn run_pipeline(&mut self, program: &mut Program, full_mode: bool) {
        // ── Stage 1: Semantic Rewrites (gnn-optimizer) ────────────────────
        #[cfg(feature = "gnn-optimizer")]
        {
            let mut semantic = SemanticSuperoptimizer::new();
            let patterns_before = semantic.patterns_matched;
            semantic.optimize_program(program);
            let patterns_after = semantic.patterns_matched;
            self.stats.semantic_rewrites += (patterns_after - patterns_before) as usize;
        }

        // ── Stages 2-5: Per-expression MCTS + verification + cost ────────
        self.walk_program(program, full_mode);
    }

    // ─────────────────────────────────────────────────────────────────────
    // AST walker — visits every expression in the program
    // ─────────────────────────────────────────────────────────────────────

    /// Walk the entire program and optimize each eligible expression.
    fn walk_program(&mut self, program: &mut Program, full_mode: bool) {
        for item in &mut program.items {
            self.walk_item(item, /* is_hot */ false, full_mode);
        }
    }

    fn walk_item(&mut self, item: &mut Item, is_hot: bool, full_mode: bool) {
        match item {
            Item::Fn(fn_decl) => {
                // Function bodies are considered "warm" — they may be called
                // multiple times, so optimization is worthwhile.
                if let Some(body) = &mut fn_decl.body {
                    self.walk_block(body, is_hot || true, full_mode);
                }
            }
            Item::System(sys_decl) => {
                // System bodies run every tick — always hot.
                self.walk_block(&mut sys_decl.body, true, full_mode);
            }
            Item::Const(const_decl) => {
                self.walk_expr(&mut const_decl.value, is_hot, full_mode);
            }
            _ => {
                // Structs, enums, components, etc. have no executable bodies.
            }
        }
    }

    fn walk_block(&mut self, block: &mut crate::compiler::ast::Block, is_hot: bool, full_mode: bool) {
        for stmt in &mut block.stmts {
            self.walk_stmt(stmt, is_hot, full_mode);
        }
        if let Some(tail) = &mut block.tail {
            self.walk_expr(tail, is_hot, full_mode);
        }
    }

    fn walk_stmt(&mut self, stmt: &mut Stmt, is_hot: bool, full_mode: bool) {
        match stmt {
            Stmt::Let { init: Some(expr), .. } => {
                self.walk_expr(expr, is_hot, full_mode);
            }
            Stmt::Expr { expr, .. } => {
                self.walk_expr(expr, is_hot, full_mode);
            }
            Stmt::Return { value: Some(expr), .. } => {
                self.walk_expr(expr, is_hot, full_mode);
            }
            Stmt::If { cond, then, else_, .. } => {
                self.walk_expr(cond, is_hot, full_mode);
                self.walk_block(then, is_hot, full_mode);
                if let Some(else_box) = else_ {
                    match else_box.as_mut() {
                        crate::compiler::ast::IfOrBlock::If(nested_if) => {
                            self.walk_stmt(nested_if, is_hot, full_mode);
                        }
                        crate::compiler::ast::IfOrBlock::Block(b) => {
                            self.walk_block(b, is_hot, full_mode);
                        }
                    }
                }
            }
            Stmt::While { cond, body, .. } => {
                self.walk_expr(cond, true, full_mode);
                self.walk_block(body, true, full_mode);
            }
            Stmt::Loop { body, .. } => {
                self.walk_block(body, true, full_mode);
            }
            Stmt::ForIn { iter, body, .. } => {
                self.walk_expr(iter, true, full_mode);
                self.walk_block(body, true, full_mode);
            }
            Stmt::EntityFor { body, .. } => {
                self.walk_block(body, true, full_mode);
            }
            Stmt::Match { expr, arms, .. } => {
                self.walk_expr(expr, is_hot, full_mode);
                for arm in arms.iter_mut() {
                    if let Some(guard) = &mut arm.guard {
                        self.walk_expr(guard, is_hot, full_mode);
                    }
                    self.walk_expr(&mut arm.body, is_hot, full_mode);
                }
            }
            Stmt::Break { value: Some(expr), .. } => {
                self.walk_expr(expr, is_hot, full_mode);
            }
            Stmt::Item(item_box) => {
                self.walk_item(item_box, is_hot, full_mode);
            }
            _ => {
                // Let with no init, Break with no value, etc.
            }
        }
    }

    /// Walk and potentially optimize a single expression node, recursing
    /// into children first (bottom-up optimization).
    fn walk_expr(&mut self, expr: &mut Expr, is_hot: bool, full_mode: bool) {
        self.stats.expressions_visited += 1;

        // ── Recurse into children first (bottom-up) ──────────────────────
        self.recurse_into_children(expr, is_hot, full_mode);

        // ── Try to optimize this expression ──────────────────────────────
        self.try_optimize_expr(expr, is_hot, full_mode);
    }

    /// Recursively walk into child expressions.
    fn recurse_into_children(&mut self, expr: &mut Expr, is_hot: bool, full_mode: bool) {
        match expr {
            Expr::BinOp { lhs, rhs, .. } => {
                self.walk_expr(lhs, is_hot, full_mode);
                self.walk_expr(rhs, is_hot, full_mode);
            }
            Expr::UnOp { expr: inner, .. } => {
                self.walk_expr(inner, is_hot, full_mode);
            }
            Expr::Assign { target, value, .. } => {
                self.walk_expr(target, is_hot, full_mode);
                self.walk_expr(value, is_hot, full_mode);
            }
            Expr::Field { object, .. } => {
                self.walk_expr(object, is_hot, full_mode);
            }
            Expr::Index { object, indices, .. } => {
                self.walk_expr(object, is_hot, full_mode);
                for idx in indices.iter_mut() {
                    self.walk_expr(idx, is_hot, full_mode);
                }
            }
            Expr::Call { func, args, named, .. } => {
                self.walk_expr(func, is_hot, full_mode);
                for arg in args.iter_mut() {
                    self.walk_expr(arg, is_hot, full_mode);
                }
                for (_, val) in named.iter_mut() {
                    self.walk_expr(val, is_hot, full_mode);
                }
            }
            Expr::MethodCall { receiver, args, .. } => {
                self.walk_expr(receiver, is_hot, full_mode);
                for arg in args.iter_mut() {
                    self.walk_expr(arg, is_hot, full_mode);
                }
            }
            Expr::VecCtor { elems, .. } | Expr::ArrayLit { elems, .. } => {
                for elem in elems.iter_mut() {
                    self.walk_expr(elem, is_hot, full_mode);
                }
            }
            Expr::IfExpr { cond, then, else_, .. } => {
                self.walk_expr(cond, is_hot, full_mode);
                self.walk_block(then, is_hot, full_mode);
                if let Some(else_block) = else_ {
                    self.walk_block(else_block, is_hot, full_mode);
                }
            }
            Expr::Closure { body, .. } => {
                self.walk_expr(body, is_hot, full_mode);
            }
            Expr::Block(block) => {
                self.walk_block(block, is_hot, full_mode);
            }
            Expr::Tuple { elems, .. } => {
                for elem in elems.iter_mut() {
                    self.walk_expr(elem, is_hot, full_mode);
                }
            }
            Expr::Cast { expr: inner, .. } => {
                self.walk_expr(inner, is_hot, full_mode);
            }
            Expr::MatMul { lhs, rhs, .. }
            | Expr::HadamardMul { lhs, rhs, .. }
            | Expr::HadamardDiv { lhs, rhs, .. }
            | Expr::TensorConcat { lhs, rhs, .. }
            | Expr::KronProd { lhs, rhs, .. }
            | Expr::OuterProd { lhs, rhs, .. } => {
                self.walk_expr(lhs, is_hot, full_mode);
                self.walk_expr(rhs, is_hot, full_mode);
            }
            Expr::Grad { inner, .. } => {
                self.walk_expr(inner, is_hot, full_mode);
            }
            Expr::Pow { base, exp, .. } => {
                self.walk_expr(base, is_hot, full_mode);
                self.walk_expr(exp, is_hot, full_mode);
            }
            Expr::Range { lo, hi, .. } => {
                if let Some(lo) = lo {
                    self.walk_expr(lo, is_hot, full_mode);
                }
                if let Some(hi) = hi {
                    self.walk_expr(hi, is_hot, full_mode);
                }
            }
            Expr::StructLit { fields, .. } => {
                for (_, val) in fields.iter_mut() {
                    self.walk_expr(val, is_hot, full_mode);
                }
            }
            // Leaf nodes — no children to recurse into.
            Expr::IntLit { .. }
            | Expr::FloatLit { .. }
            | Expr::BoolLit { .. }
            | Expr::StrLit { .. }
            | Expr::Ident { .. }
            | Expr::Path { .. } => {}
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // Core per-expression optimization pipeline
    // ─────────────────────────────────────────────────────────────────────

    /// Try to optimize a single expression through stages 2-5.
    ///
    /// Returns `true` if the expression was replaced with a better one.
    fn try_optimize_expr(&mut self, expr: &mut Expr, is_hot: bool, full_mode: bool) -> bool {
        // ── Convert Expr → MctsInstr ─────────────────────────────────────
        //
        // Only pure arithmetic/logical expressions can be optimized.
        // Anything involving calls, field access, assignments, etc. is
        // skipped because the MCTS search space doesn't model side effects.

        #[cfg(any(feature = "core-superopt", feature = "gnn-optimizer"))]
        {
            let original_instr = match MctsInstr::from_expr(expr) {
                Some(instr) => instr,
                None => return false, // Can't represent in MCTS search space.
            };

            // Skip expressions that are too large (MCTS would be too slow).
            if instr_size(&original_instr) > self.config.max_expr_size {
                return false;
            }

            // Skip trivially simple expressions (single constants/variables).
            if !is_interesting_for_superopt(&original_instr) {
                return false;
            }

            // ── Stage 3: MCTS Tree Search ────────────────────────────────
            // S10 fix: Reuse MctsSuperoptimizer across expressions instead of
            // creating a new one per expression (which runs CPUID each time).
            // S11 fix: Use hotpath() config instead of maximum() even for hot
            // expressions — maximum() has 5000 sims and 1s budget per expr!
            let mcts_config = if is_hot {
                MctsConfig::hotpath() // Was maximum() — 5000 sims × 1s = too slow
            } else {
                MctsConfig::fast()
            };

            // Fix H3: Only recreate the MCTS optimizer when needed.
            // Previously, BOTH branches of the if/else created a new optimizer,
            // wasting CPUID/HardwareCostModel initialization cost every expression.
            // Now we call reset_for_new_expr() to reuse the existing optimizer
            // when only the expression changes (not the config).
            let need_new_optimizer = match &self.mcts_optimizer {
                None => true,
                Some(existing) => existing.config_hash() != mcts_config.config_hash(),
            };

            if need_new_optimizer || self.mcts_optimizer.is_none() {
                self.mcts_optimizer = Some(MctsSuperoptimizer::new(mcts_config));
            } else {
                // Reuse the existing optimizer — just reset for the new expression.
                // This avoids re-initializing CPUID, hardware cost model, etc.
                self.mcts_optimizer.as_mut().unwrap().reset_for_new_expr();
            }

            let candidate_expr = match self.mcts_optimizer.as_mut().unwrap().optimize(expr) {
                Some(e) => e,
                None => return false, // No improvement found.
            };
            self.stats.mcts_candidates_generated += 1;

            // Convert candidate to Instr for verification stages.
            let candidate_instr = match MctsInstr::from_expr(&candidate_expr) {
                Some(instr) => instr,
                None => return false, // Candidate can't be represented? Skip.
            };

            // ── Stage 2: Known-Bits Pruning ──────────────────────────────
            #[cfg(feature = "core-superopt")]
            {
                let env = FxHashMap::default(); // No variable type info available.
                if !known_bits::may_be_equivalent(&original_instr, &candidate_instr, &env) {
                    self.stats.known_bits_rejections += 1;
                    return false;
                }
            }

            // ── Stage 4: SMT Verification ────────────────────────────────
            #[cfg(feature = "core-superopt")]
            {
                if self.config.verify_equivalence && full_mode {
                    let num_vars = original_instr
                        .variables()
                        .len()
                        .max(candidate_instr.variables().len());
                    let mut verifier =
                        CegisVerifier::new(self.config.smt_bitwidth, num_vars, self.config.cegis_max_iterations);
                    let result = verifier.verify(&original_instr, &candidate_instr);
                    self.stats.smt_verifications += 1;
                    match result {
                        VerifyResult::Equivalent => {
                            // Proven equivalent — proceed to cost check.
                        }
                        VerifyResult::CounterExample(_) => {
                            // NOT equivalent — reject.
                            return false;
                        }
                        VerifyResult::Timeout => {
                            // Could not prove in time — be conservative, reject.
                            return false;
                        }
                        VerifyResult::Inconclusive(_) => {
                            // Without Z3, test-vector filter passed but no
                            // formal proof. In full_mode we require proof; in
                            // fast mode we accept test-vector-only validation.
                            if full_mode {
                                return false;
                            }
                            // In fast mode, accept the candidate on the basis
                            // of the test-vector filter alone.
                        }
                    }
                }
            }

            // When core-superopt is not enabled, we rely on MCTS's own
            // internal test-vector verification (happens inside
            // `MctsSuperoptimizer::optimize`). No additional check needed.

            // ── Stage 5: uarch Cost Validation ───────────────────────────
            #[cfg(feature = "core-superopt")]
            {
                if self.config.use_uarch_cost_model {
                    // S13 fix: Cache TargetConfig instead of calling detect()
                    // (which executes CPUID) per expression.
                    let target = *self.cached_target.get_or_insert_with(TargetConfig::detect);
                    let original_cost = estimate_instr_cycles(&original_instr, target);
                    let candidate_cost = estimate_instr_cycles(&candidate_instr, target);

                    // Only accept if the candidate is strictly cheaper.
                    // (Equal cost rewrites are rejected to avoid churn.)
                    if candidate_cost >= original_cost {
                        self.stats.uarch_rejections += 1;
                        return false;
                    }
                }
            }

            // ── Stage 6: Machine-Instruction-Aware Optimization ────────
            //
            // When the machine-instr-model feature is enabled, lower the
            // candidate to machine instructions and run the instruction-aware
            // pipeline: legality check → multi-objective cost model →
            // bounded validation. This catches cases where the expression-level
            // MCTS found something that looks good algebraically but is worse
            // at the machine level (e.g., more spills, worse port pressure).
            #[cfg(feature = "machine-instr-model")]
            {
                self.stats.machine_instr_candidates += 1;

                // Lower both original and candidate to machine instruction blocks
                let orig_block = lower_instr_to_machine(&original_instr);
                let cand_block = lower_instr_to_machine(&candidate_instr);

                // Run the machine-instr pipeline on the candidate
                let target = *self.cached_target.get_or_insert_with(TargetConfig::detect);
                let pipeline = MachineInstrPipeline::new(target);

                // Score both blocks with the multi-objective cost model
                let orig_cost = estimate_machine_cost(&orig_block, target);
                let cand_cost = estimate_machine_cost(&cand_block, target);

                // Reject if the machine-level cost is not better
                if cand_cost.weighted_cost() >= orig_cost.weighted_cost() {
                    self.stats.machine_instr_rejections += 1;
                    return false;
                }

                // Validate the transformation at the machine level
                let valid = validate_transformation(
                    &orig_block, &cand_block, pipeline.validation_tests,
                );
                match valid {
                    crate::optimizer::machine_instr_model::ValidationResult::ProvenEquivalent
                    | crate::optimizer::machine_instr_model::ValidationResult::BoundedTestPassed { .. } => {
                        // Machine-level validation passed
                    }
                    _ => {
                        // Machine-level validation failed — reject
                        self.stats.machine_instr_rejections += 1;
                        return false;
                    }
                }
            }

            // ── All checks passed — apply the optimization ───────────────
            self.stats.mcts_candidates_verified += 1;
            self.stats.expressions_optimized += 1;
            *expr = candidate_expr;
            return true;
        }

        #[cfg(not(any(feature = "core-superopt", feature = "gnn-optimizer")))]
        {
            let _ = (expr, is_hot, full_mode);
            false
        }
    }
}

// =========================================================================
// Helper functions
// =========================================================================

/// Count the number of nodes in an `Instr` tree.
#[cfg(any(feature = "core-superopt", feature = "gnn-optimizer"))]
fn instr_size(instr: &MctsInstr) -> usize {
    match instr {
        MctsInstr::ConstInt(_)
        | MctsInstr::ConstFloat(_)
        | MctsInstr::ConstBool(_)
        | MctsInstr::Var(_) => 1,
        MctsInstr::BinOp { lhs, rhs, .. } => 1 + instr_size(lhs) + instr_size(rhs),
        MctsInstr::UnOp { operand, .. } => 1 + instr_size(operand),
    }
}

/// Check if an instruction tree is "interesting" enough to warrant
/// superoptimization.  Single constants or bare variables have no room
/// for improvement.
#[cfg(any(feature = "core-superopt", feature = "gnn-optimizer"))]
fn is_interesting_for_superopt(instr: &MctsInstr) -> bool {
    matches!(
        instr,
        MctsInstr::BinOp { .. } | MctsInstr::UnOp { .. }
    )
}

// ─────────────────────────────────────────────────────────────────────────
// Instr → MachineInstr lowering for uarch cost estimation
// ─────────────────────────────────────────────────────────────────────────

/// Convert an `Instr` tree into a flat sequence of `MachineInstr`s in
/// SSA form, then estimate the cycle count using the uarch cost model.
#[cfg(feature = "core-superopt")]
fn estimate_instr_cycles(instr: &MctsInstr, target: TargetConfig) -> f64 {
    let mut machine_instrs: Vec<MachineInstr> = Vec::new();
    let mut next_reg: u8 = 0;
    lower_instr_to_ssa(instr, &mut machine_instrs, &mut next_reg);
    uarch_cost::estimate_block_cycles(&machine_instrs, target)
}

/// Recursively lower an `Instr` tree into SSA `MachineInstr`s.
///
/// Returns the virtual register number that holds the result of this
/// instruction subtree.
#[cfg(feature = "core-superopt")]
fn lower_instr_to_ssa(instr: &MctsInstr, out: &mut Vec<MachineInstr>, next_reg: &mut u8) -> u8 {
    let dst = alloc_reg(next_reg);

    match instr {
        MctsInstr::ConstInt(v) => {
            // Use the low 32 bits as an immediate when possible.
            let imm = (*v as u32) as i32;
            out.push(MachineInstr {
                opcode: Opcode::LoadConst,
                dst,
                src1: 0,
                src2: 0,
                imm,
                has_imm: true,
            });
        }
        MctsInstr::ConstFloat(bits) => {
            out.push(MachineInstr {
                opcode: Opcode::LoadConst,
                dst,
                src1: 0,
                src2: 0,
                imm: *bits as i32,
                has_imm: true,
            });
        }
        MctsInstr::ConstBool(b) => {
            out.push(MachineInstr {
                opcode: Opcode::LoadConst,
                dst,
                src1: 0,
                src2: 0,
                imm: if *b { 1 } else { 0 },
                has_imm: true,
            });
        }
        MctsInstr::Var(_) => {
            // Variable load — modeled as a mov from an input register.
            // We use the destination register as a placeholder since we
            // don't have a real register allocator here.
            out.push(MachineInstr {
                opcode: Opcode::Mov,
                dst,
                src1: dst,
                src2: 0,
                imm: 0,
                has_imm: false,
            });
        }
        MctsInstr::BinOp { op, lhs, rhs } => {
            let src1 = lower_instr_to_ssa(lhs, out, next_reg);
            let src2 = lower_instr_to_ssa(rhs, out, next_reg);
            let opcode = binop_to_opcode(*op);
            out.push(MachineInstr {
                opcode,
                dst,
                src1,
                src2,
                imm: 0,
                has_imm: false,
            });
        }
        MctsInstr::UnOp { op, operand } => {
            let src1 = lower_instr_to_ssa(operand, out, next_reg);
            let opcode = unop_to_opcode(*op);
            out.push(MachineInstr {
                opcode,
                dst,
                src1,
                src2: 0,
                imm: 0,
                has_imm: false,
            });
        }
    }

    dst
}

/// Allocate a new virtual register number.
#[cfg(feature = "core-superopt")]
fn alloc_reg(next_reg: &mut u8) -> u8 {
    let r = *next_reg;
    *next_reg = next_reg.wrapping_add(1);
    r
}

/// Map an AST binary operator to a uarch cost opcode.
#[cfg(feature = "core-superopt")]
fn binop_to_opcode(op: crate::compiler::ast::BinOpKind) -> Opcode {
    use crate::compiler::ast::BinOpKind;
    match op {
        BinOpKind::Add => Opcode::Add,
        BinOpKind::Sub => Opcode::Sub,
        BinOpKind::Mul => Opcode::Mul,
        BinOpKind::Div => Opcode::Div,
        BinOpKind::Rem => Opcode::Rem,
        BinOpKind::BitAnd => Opcode::And,
        BinOpKind::BitOr => Opcode::Or,
        BinOpKind::BitXor => Opcode::Xor,
        BinOpKind::Shl => Opcode::Shl,
        BinOpKind::Shr => Opcode::Shr,
        // Comparisons map to CMP; logical ops also map to CMP-like for cost.
        BinOpKind::Eq
        | BinOpKind::Ne
        | BinOpKind::Lt
        | BinOpKind::Le
        | BinOpKind::Gt
        | BinOpKind::Ge => Opcode::Cmp,
        BinOpKind::And | BinOpKind::Or => Opcode::Test,
        BinOpKind::FloorDiv => Opcode::Div,
    }
}

/// Map an AST unary operator to a uarch cost opcode.
#[cfg(feature = "core-superopt")]
fn unop_to_opcode(op: crate::compiler::ast::UnOpKind) -> Opcode {
    use crate::compiler::ast::UnOpKind;
    match op {
        UnOpKind::Neg => Opcode::Neg,
        UnOpKind::Not => Opcode::Not,
        UnOpKind::Deref | UnOpKind::Ref | UnOpKind::RefMut => Opcode::Mov,
    }
}

// =========================================================================
// Hardware-Calibrated Cost Model
//
// Bridges the gap between the STATIC uarch cost model (uops.info tables)
// and the REAL hardware behavior measured via Linux perf_event_open.
//
// The problem: the static cost model assumes ideal conditions (no cache
// misses, no branch mispredictions, no memory stalls). Real code has all
// of these. The HW-calibrated model:
//   1. Runs a calibration micro-benchmark on the current CPU
//   2. Measures actual IPC, cache miss rates, branch misprediction rates
//   3. Computes scaling factors for the static cost model
//   4. Adjusts the superoptimizer's cost estimates to reflect reality
//
// This prevents the superoptimizer from choosing transformations that
// look good on paper (fewer uops, shorter dependency chain) but are
// actually slower on real hardware (because they thrash the cache or
// cause branch mispredictions).
// =========================================================================

/// Calibration data from hardware performance counters.
///
/// This struct captures the ratio between observed (real) and predicted
/// (static) costs, which can be used to scale the superoptimizer's
/// cost estimates.
#[derive(Debug, Clone)]
#[cfg(feature = "core-superopt")]
pub struct HwCalibrationData {
    /// Observed instructions per cycle (measured via perf).
    pub observed_ipc: f64,
    /// Theoretical maximum IPC (from uarch model: 4 for Skylake, 6 for Golden Cove, etc.).
    pub theoretical_max_ipc: f64,
    /// Cache miss rate as fraction of all cache references.
    pub cache_miss_rate: f64,
    /// Branch misprediction rate as fraction of all branch instructions.
    pub branch_mispred_rate: f64,
    /// Scaling factor for latency estimates.
    /// >1.0 means real code is slower than predicted (cache misses, stalls).
    /// Computed as: theoretical_max_ipc / observed_ipc.max(0.01)
    pub latency_scale: f64,
    /// Memory stall penalty (extra cycles per cache miss beyond L1 latency).
    pub memory_stall_cycles: f64,
    /// Whether this calibration was derived from real hardware counters
    /// (as opposed to defaults/simulated values).
    pub from_real_hw: bool,
}

#[cfg(feature = "core-superopt")]
impl Default for HwCalibrationData {
    fn default() -> Self {
        Self {
            observed_ipc: 2.0,     // Conservative default: modern CPUs rarely sustain >2 IPC on real workloads
            theoretical_max_ipc: 4.0,
            cache_miss_rate: 0.05,  // 5% is typical for compute-heavy code
            branch_mispred_rate: 0.02, // 2% is typical for well-predicted code
            latency_scale: 2.0,    // Real code ~2x slower than ideal due to stalls
            memory_stall_cycles: 40.0, // ~40 cycles for L2 miss → L3 → DRAM
            from_real_hw: false,
        }
    }
}

#[cfg(feature = "core-superopt")]
impl HwCalibrationData {
    /// Calibrate from real hardware performance counters.
    ///
    /// Uses the `HwFeedbackCollector` to measure actual IPC, cache miss
    /// rates, and branch misprediction rates, then computes scaling
    /// factors for the superoptimizer's cost model.
    pub fn calibrate_from_hw() -> Self {
        use crate::compiler::hw_feedback::{
            HwFeedbackCollector, HwFeedbackAnalyzer, PebsConfig,
        };

        let mut collector = HwFeedbackCollector::new(PebsConfig::default());
        let analyzer = HwFeedbackAnalyzer::new(0.1);

        // Start profiling, run a quick calibration workload, then stop.
        let start_ok = collector.start_profiling().is_ok();
        if !start_ok {
            return Self::default();
        }

        // Calibration workload: simple compute-heavy loop that exercises
        // the same kinds of operations the superoptimizer will encounter.
        let mut sink: u64 = 0;
        for i in 0u64..1_000_000 {
            sink = sink.wrapping_add(i.wrapping_mul(7919) ^ (i >> 3));
        }
        std::hint::black_box(sink);

        let profile = match collector.stop_profiling() {
            Ok(p) => p,
            Err(_) => return Self::default(),
        };

        let metrics = analyzer.analyze(&profile);

        // Compute the theoretical max IPC from the detected microarchitecture.
        let theoretical_max_ipc = {
            use crate::optimizer::uarch_cost::TargetConfig;
            let target = TargetConfig::detect();
            target.decode_width as f64
        };

        // The latency scale represents how much slower real code is
        // compared to the ideal model.  If observed IPC is 1.5 but
        // theoretical max is 4.0, then real code takes 4.0/1.5 = 2.67x
        // longer than predicted.
        let latency_scale = theoretical_max_ipc / metrics.ipc.max(0.01);

        // Memory stall cycles: each L2 miss costs ~40 cycles (L3 hit)
        // or ~200 cycles (DRAM).  We estimate from the cache miss rate
        // and a conservative L2 miss penalty of 40 cycles.
        let memory_stall_cycles = if metrics.cache_miss_rate > 0.0 {
            // At 5% miss rate with 40-cycle penalty, that's ~2 extra
            // cycles per instruction on average. Scale linearly.
            40.0 * (metrics.cache_miss_rate / 0.05)
        } else {
            0.0
        };

        Self {
            observed_ipc: metrics.ipc,
            theoretical_max_ipc,
            cache_miss_rate: metrics.cache_miss_rate,
            branch_mispred_rate: metrics.branch_mispred_rate,
            latency_scale,
            memory_stall_cycles,
            from_real_hw: true,
        }
    }

    /// Apply this calibration to a static cycle estimate.
    ///
    /// The static model gives ideal-cycle counts (no stalls, no cache
    /// misses). This function scales them to reflect real hardware:
    ///
    ///   calibrated_cycles = static_cycles * latency_scale
    ///
    /// The scale factor is derived from observed IPC vs theoretical max,
    /// which captures cache misses, branch mispredictions, and memory
    /// stalls in a single number.
    #[inline]
    pub fn calibrate_cycles(&self, static_cycles: f64) -> f64 {
        static_cycles * self.latency_scale
    }
}

/// A superoptimizer cost model that uses hardware calibration to adjust
/// static cycle estimates.  This replaces the naive static-only model
/// that ignores cache misses, branch mispredictions, and memory stalls.
#[derive(Debug, Clone)]
#[cfg(feature = "core-superopt")]
pub struct HwCalibratedCostModel {
    /// The hardware calibration data (from real counters or defaults).
    pub calibration: HwCalibrationData,
    /// Whether to use hardware calibration (true) or pure static model (false).
    pub use_hw_calibration: bool,
}

#[cfg(feature = "core-superopt")]
impl Default for HwCalibratedCostModel {
    fn default() -> Self {
        Self {
            calibration: HwCalibrationData::default(),
            use_hw_calibration: true,
        }
    }
}

#[cfg(feature = "core-superopt")]
impl HwCalibratedCostModel {
    /// Create a new cost model with hardware calibration.
    pub fn new() -> Self {
        let calibration = HwCalibrationData::calibrate_from_hw();
        Self {
            calibration,
            use_hw_calibration: true,
        }
    }

    /// Create a pure static cost model (no hardware calibration).
    pub fn static_only() -> Self {
        Self {
            calibration: HwCalibrationData::default(),
            use_hw_calibration: false,
        }
    }

    /// Estimate the cost of an instruction sequence, optionally calibrated
    /// by real hardware performance data.
    pub fn estimate(
        &self,
        instrs: &[crate::optimizer::uarch_cost::MachineInstr],
        target: crate::optimizer::uarch_cost::TargetConfig,
    ) -> f64 {
        let static_cycles = crate::optimizer::uarch_cost::estimate_block_cycles(instrs, target);
        if self.use_hw_calibration {
            self.calibration.calibrate_cycles(static_cycles)
        } else {
            static_cycles
        }
    }
}
